# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
# -   repo: https://github.com/Bahjat/pre-commit-golang
    rev: v3.3.0
    hooks:
    # - id: go-vet
    # - id: golangci-lint
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: trailing-whitespace
    name: Trim Trailing Whitespace
    entry: trailing-whitespace-fixer
    language: Golang
    pass_filenames: false
