# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: name-tests-test
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: trailing-whitespace
    name: Trim Trailing Whitespace
    entry: trailing-whitespace-fixer
    language: Golang
    pass_filenames: false
